### ISSUE TITLE
LoginView Problem

### ISSUE THREAD

**Issue by jihyuky** [Accusamus2065/CSC207-Project#40]
When switching from the WelcomeView to the LoginView, the LoginView opens in a new window instead of swapping the view from WelcomeView to LoginView. I think this is a LoginView problem, and maybe it is because I didn't use the swapviews method?

I do not think it is WelcomePresenter's problem because SignupView is loaded correctly, so it is most likely the LoginViews problem.

- [ ] Check what is causing this error by going through the View and comparing it with other views.
- [ ] Fix this error by fixing the implementation of LoginView.

**Comment by taml5** [comment]
The issue is caused by the fact that `LoginView` has a new `JFrame` which is being used instead—the fix would be to simply remove all mentions of `frame`, make `LoginView` extend `JPanel`, and change all references from `panel`  to `this`.
