### ISSUE TITLE
Use case choosepatient currently implements three use cases concurrently which need to be separated out to follow SOLID and the CA

### ISSUE THREAD

**Issue by taml5** [Accusamus2065/CSC207-Project#44]
Currently, the use case `choosepatient` does three things:

1. Logout from `ListOfPatientsView`
2. ModifyPatient which should be in `PatientsChatWithBotView` since that modifies a patient instance, whereas `ListOfPatientsView` is a view that should only be seen by doctors
3. ChoosePatient from `ListOfPatientsView`

All three of these use cases need to have their own sequence, i.e. their own `Controller`, `Presenter`, `Interactor`, etc. as well as their own `UseCaseFactories`.

- [ ] Separate `Logout` use case
- [ ] Separate `ModifyPatient` use case
- [ ] Separate `ChoosePatient` use case

**Comment by taml5** [comment]
- [ ] Separate `Logout` use case
- [ ] Separate `ModifyPatient` use case
- [ ] Separate `ChoosePatient` use case

**Comment by jihyuky** [comment]
This was my usecase, I recognize that this does not follow the Single Responsibility Principle from SOLID. Could I be assigned to work on this?
